version: '3'

services:
  db:
    image: postgres
    build:
      context: postgres
      dockerfile: Dockerfile
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  microservice:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - variables.env
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
#      - rabbitmq

#  receive_messages:
#
#  refresh_leaderboardview:

#  mock_sender:

#  rabbitmq:
