# Generated by Django 3.0.4 on 2020-04-07 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE MATERIALIZED VIEW leaderboard_view AS
            SELECT row_number() OVER(ORDER BY rating DESC, date_time) AS position, user_id AS id, rating, date_time 
            FROM leaderboard_leaderboard;
            CREATE UNIQUE INDEX leaderboard_view_position_index ON leaderboard_view(position);
            """
        ),
        migrations.CreateModel(
            name='LeaderBoardView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'leaderboard_view',
                'managed': False,
            },
        ),
    ]
