# Generated by Django 3.0.4 on 2020-03-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaderboard',
            options={'ordering': ['rating', '-date_time']},
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
