# Generated by Django 3.0.4 on 2020-04-03 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0003_remove_leaderboard_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaderboard',
            options={'ordering': ('rating', 'date_time')},
        ),
    ]
